adding a bit of stability: -eu to fail if smth is wrong, some error msgs if # of params is wrong, a bit of added indentation consistency

diff --git a/git-bzr b/git-bzr
--- a/git-bzr
+++ b/git-bzr
@@ -1,13 +1,16 @@
-#!/bin/sh
+#!/bin/bash
 #set -x
+
+#  Better fail completely if something goes wrong + fail if a variable is not
+#  defined
+set -eu
 
 function perror() {
  echo "$@" >&2
 }
 
-command=$1
 
-if [ "x$command" == "x" ] ; then
+if [ $# -lt 1 ] ; then
 # FIXME: commands=[:add, :push, :fetch, :pull]
 # the second condition should be && $1 not in @commands
   echo "Usage: git bzr2 [COMMAND] [OPTIONS]"
@@ -15,9 +18,15 @@ if [ "x$command" == "x" ] ; then
   exit 1
 fi
 
+command=$1
+
 return=""
 
 function add() {
+    if [ $# -lt 2 ] ; then
+        echo "Specify the name and location for 'add' command"
+        exit 1
+    fi
     name="$1"
     location="$2"
     if [[ -z "$@" ]] ; then
@@ -42,11 +51,15 @@ function add() {
 }
 
 function get_location() {
-   remote=$1
-   shift
-   args=$@
-   l="$(git config git-bzr.${remote}.location)"
-   if [ -z "$l" ] ; then
+    if [ $# -lt 1 ] ; then
+        echo "At least the name of the remote is needed for get_location"
+        exit 1
+    fi
+    remote=$1
+    shift
+    args=$@
+    l="$(git config git-bzr.${remote}.location)"
+    if [ -z "$l" ] ; then
         perror "Cannot find bazaar remote with name '${remote}'."
         exit 1
     fi
@@ -54,6 +67,10 @@ function get_location() {
 }
 
 function fetch() {
+   if [ $# -lt 1 ] ; then
+       echo "At least the name of the remote is needed for fetch"
+       exit 1
+   fi
    remote=$1
    shift
    args=$@
@@ -95,6 +112,10 @@ function fetch() {
 }
 
 function push() {
+   if [ $# -lt 1 ] ; then
+       echo "At least the name of the remote is needed for push"
+       exit 1
+   fi
    remote=$1
    shift
    args=$@
